---
title: "STATS 551 Final Project"
author: "Calder Moore"
format: pdf
editor: visual
---

## Data

Hierarchical structure comes from multiple appointments per patient IDs, i.e. no-shows (which we are interested in measuring), is nested within appointment, which is nested within patient ID. Data comes from Kaggle.

https://www.kaggle.com/datasets/joniarroba/noshowappointments

```{r, fig.width = 7, fig.height = 10}
library(brms)

noshow <- read.csv("KaggleV2-May-2016.csv")


# Want to regress No.show on 

# Find the mean and standard deviation for Age and proportion of female in the Gender variable to inform priors

mean(noshow$Age)
sd(noshow$Age)

# Set priors

priors_noshow <- c(set_prior(prior = "normal(37, 23)", class = "b", coef = "Age"))

noshow$No.show <- ifelse(noshow$No.show == "Yes", 1, 0)

# iteration default is 2000 and default chains is 4

# Try parallel processing to make it go a bit faster?

options(mc.cores = parallel::detectCores())

NoShowFit <- brm(
  No.show ~ Age + Gender + SMS_received + Scholarship + (1 | PatientId),
  data = noshow,
  prior = priors_noshow,
  family = bernoulli(),
  iter = 1400,
  warmup = 600,
  chains = 2,
  cores = 12
)

summary(NoShowFit)

plot(NoShowFit, ask = FALSE)

pp_check(NoShowFit, ndraws = 20)
```

```{r}
# Export figures and results

plot(NoShowFit, ask = FALSE)

png("Fit Plot.png", width = 800, height = 1000)
plot(NoShowFit, ask = FALSE)
dev.off()

pp_check(NoShowFit, ndraws = 20)

png("ppcheck.png", width = 800, height = 1000)
pp_check(NoShowFit, ndraws = 20)
dev.off()

# Summary stats

vars <- c("No.show", "Age", "Gender", "SMS_received", "Scholarship")

sumstats <- noshow[, vars]

library(stargazer)

stargazer(sumstats,
          type = "latex",       
          summary = TRUE,       
          out = "summary.tex")  

# Model summary

tab <- as.data.frame(posterior_summary(NoShowFit))
tab$Parameter <- rownames(tab)
rownames(tab) <- NULL

library(dplyr)

tab <- tab %>% 
  rename(
    term = Parameter,
    estimate = Estimate,
    std.error = Est.Error,
    conf.low = Q2.5,
    conf.high = Q97.5
  )


library(modelsummary)

modelsummary(
  NoShowFit,
  output = "model_summary.tex",
  statistic = c("std.error", "conf.int", "p.value"),
  estimate = "{estimate} ({std.error})"
)

```
